on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      project:
        description: "Project Name"
        required: true
        default: "pipe-hub"

name: "Terraform CI/CD"

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./projeto-final

      - name: "Terraform fmt"
        run: terraform fmt -check
        working-directory: ./projeto-final

      - name: "Terraform validate"
        run: terraform validate
        working-directory: ./projeto-final

      - name: "Terraform Plan"
        run: terraform plan
        working-directory: ./projeto-final

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./projeto-final
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}